
spring:
  security:
    user:
      name: mahi
      password: 12345
      roles: ADMIN,USER
      
      
security:
  oauth2:
    client:
      client-id: my-trusted
      client-secret: pin
      access-token-validity-seconds: 3600
      authorized-grant-types: refresh_token,authorization_code,password,client_credentials
      scope: READ,WRITE
    authorization:
      check-token-access: permitAll
        